name: Run Jest testing suite
on:
  workflow_dispatch:
  push:
    branches:
      - custom-br
    paths-ignore:
      - "**/total-rewards.txt"
  pull_request:

env:
  NODE_ENV: "test"
  TWITTER_API_KEY: "<twitter_api_key>"
  TWITTER_API_KEY_SECRET: "<twitter_api_secret>"
  TWITTER_ACCESS_TOKEN: "<twitter_access_token>"
  TWITTER_ACCESS_TOKEN_SECRET: "<twitter_access_token_secret>"

jobs:
  testing:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Testing
        run: |
          yarn
          yarn test | tee ./coverage.txt && exit ${PIPESTATUS[0]}
      - name: Jest Coverage Comment
        # Ensures this step is run even on previous step failure (e.g. test failed)
        if: always()
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: coverage/coverage-summary.json
          junitxml-path: junit.xml
          junitxml-title: JUnit
          coverage-path: ./coverage.txt
